# Site metadata
title: "Développeur en Formation - BTS SIO"
description: >-
  Étudiant en 1ère année de BTS SIO option SLAM.
  En apprentissage du développement web et logiciel.
  PHP • MySQL • HTML/CSS • JavaScript • Java

author: "Jorys Berche"
email: "jorys.berche@gmail.com"

url: "https://berche-jorys.github.io"
baseurl: "/cv-en-ligne"

social:
  github: berche-jorys
  linkedin: berche-jorys

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

collections:
  projects:
    output: false

source: docs
destination: _site

exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock